services:
  library:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db && 
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    container_name: library-service

  qcluster:
    build:
      context: .
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py qcluster"
    env_file:
      - .env
    depends_on:
      - db
    container_name: q-worker

  db:
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - library_db:$PGDATA
    container_name: postgres-db

volumes:
  library_db:
